vpu.console.print('^7            hNh          hmm             ');
vpu.console.print('^7           hNMNh       hmNmMm            ');
vpu.console.print('^7          hNMNMMh    hdNd+: Mm           ');
vpu.console.print('^7         hNMNmNMNh  dNmo:::: Md          ');
vpu.console.print('^7        hNMNmmmNMNhmMs:::::::hMd         ');
vpu.console.print('^7        mMNmmmmmNMMdNm/::::::/hMd        ');
vpu.console.print('^7       mMNmmmmmmNNMNdNm/::::::/dMd       ');
vpu.console.print('^7      dMNmmmmmmmNNNMNdNN/::::://mNh      ');
vpu.console.print('^7     hMMmmmmmmmmNNNNMNdNm+:::://+mNh     ');
vpu.console.print('^7    hNMmmmmmmmmmNNNNNMNdNN+:::///oNNh    ');
vpu.console.print('^7    mMmmmmmmmmmmNNNNNNMMdNNo::////sMm    ');
vpu.console.print('^7   dMNmmmmmmmmNNNNNNNNNMNdmNs://///hMd   ');
vpu.console.print('^7  hMNmmmmmmmmNMNNNNNNNNNMNhmM /////+dNh  ');
vpu.console.print('^7  NMmmmmmmmNMNNMNNNNNNNMNd  dMh/////oNmh ');
vpu.console.print('^7 dMNmmmmmmNMmhhNMNNNNMNd     dMm+//// Md ');
vpu.console.print('^7hNMddmmmmMMd   hMMNMNdh       hNNo///+mMm');
vpu.console.print('^7dMmddmmNMmh     hNNdh           mMh+/+ Mm');
vpu.console.print('^7NMmdmNMNh        hh              dNms+oNN');         
vpu.console.print('^7MNmmNNd                           hmNm NN');         
vpu.console.print('^7mMMNd                               hdmmh');
