#######################################################
# TOC.PY
#######################################################
# Do not modify - Will Result in Ban for your account #
#######################################################
titles = [
    {
        'name' : 'Xargoon',
        'description' : "An awesome Space shooter",
        'url' : 'xargoon.zip',
        'picture' : 'xargoon' ,
        'genre' : 'space shooter',
        'font' : 'sega',
        'multiplayer' : False,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : False,
        'keyboard' : True,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0xDEADBEEFDEADBABACAFECAFEC0C0CACA,        
    },{
        'name' : 'Axzle',
        'description' : "Mix minesweeper and pictionary in a single concept. That's the thing.",
        'url' : 'axzle.zip',
        'picture' : 'axzle' ,
        'genre' : 'puzzle',
        'font' : 'sega',
        'multiplayer' : False,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : True,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0xBABEBABEBABEBABECAFECAFEC0C0CACA,        
    },{
        'name' : 'Trickynoid',
        'description' : "Typical Bricks, Ball and paddle game.",
        'url' : 'trickynoid.zip',
        'picture' : 'trickynoid' ,
        'genre' : 'arcade',
        'font' : 'sega',
        'multiplayer' : False,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : True,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x71717171717171717171717171717171,        
    },{
        'name' : 'Snake',
        'description' : "Eat everything you can before crashing with your own body",
        'url' : 'snake.zip',
        'picture' : 'snake' ,
        'genre' : 'action puzzle',
        'font' : 'sega',
        'multiplayer' : False,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : False,
        'keyboard' : True,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x71717171717171717171715551515151, 
    },{
        'name' : 'Tri-Triad',
        'description' : "Multiplayer Card game, inspired on a famous RPG's mini-game.",
        'url' : 'tritriad.zip',
        'picture' : 'tritriad' ,
        'genre' : 'strategy',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    },{
        'name' : 'Mini Golf',
        'description' : "Insert those balls in the hole!",
        'url' : 'minigolf.zip',
        'picture' : 'minigolf' ,
        'genre' : 'arcade',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    },{
        'name' : 'Rocks & Crystals',
        'description' : "Pick all the crystals without dying because of the rocks",
        'url' : 'rocksncrystals.zip',
        'picture' : 'rocksncrystals' ,
        'genre' : 'puzzle',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    },{
        'name' : 'Tetrax',
        'description' : "The most famous 4 block piece puzzle in the world",
        'url' : 'tetrax.zip',
        'picture' : 'tetrax' ,
        'genre' : 'puzzle',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    },{
        'name' : 'Bubble Splitters',
        'description' : "Pang re-imagined. Shoot the alien bubbles until they are erradicated",
        'url' : 'bubblesplitters.zip',
        'picture' : 'bubblesplitters' ,
        'genre' : 'action puzzle',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    },{
        'name' : 'Pookman',
        'description' : "It's Just a Dirty Pacman clone",
        'url' : 'pookman.zip',
        'picture' : 'pooman' ,
        'genre' : 'arcade',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    },{
        'name' : 'RePeGe',
        'description' : "Classic roleplaying.",
        'url' : 'repege.zip',
        'picture' : 'repege' ,
        'genre' : 'arcade',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    },{
        'name' : 'WetPipes',
        'description' : "Pipes and Water, sooo fun.",
        'url' : 'wetpipes.zip',
        'picture' : 'wetpipes' ,
        'genre' : 'arcade',
        'font' : 'sega',
        'multiplayer' : True,
        'cooperative' : False,
        'joystick' : True,
        'mouse' : True,
        'keyboard' : False,
        'rating' : 5,
        'released' : '1-6-2021',
        'status' : 'beta',
        'version' : 14.32,
        'parent' : None,
        'downloaded' : False,
        'developer' : 'Black Hat Cat Studio',
        'title_key' : 0x81818181818181818187885858585858, 
    }
]

def load():
    import blackbox
    for title in titles:
        blackbox.addtitle(
            title['name'], 
            title['description'], 
            title['developer'], 
            title['url'], 
            title['picture'], 
            title['genre'], 
            title['font'], 
            title['multiplayer'], 
            title['cooperative'], 
            title['joystick'], 
            title['mouse'], 
            title['keyboard'], 
            title['rating'], 
            title['released'], 
            title['parent'] if title['parent'] else ""
        )
