# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 16 Feb 2021 23:27:43 +0000
*               @ALL          0
*               @user         8
