# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 16 Feb 2021 23:27:43 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

smiker:$2y$10$WN78xm7Ilejdzgof6PvQe.fZQVSl5zGEfLDuqRWAod8VygBt8pBTG:Smiker Pinakle AKA Sumikeru Pinakure:pinakure@gmail.com:admin,user
