const char *codepageName[] = { 	
	//SCANCODE		ASCII CODES		SHIFT ASCII			ALTGR ASCII
	"KB_TAB"		,"32"				,"32"				,"32"			,
	"KB_A"			,"ASCII_a"			,"ASCII_A"			,"ASCII_a"		,
	"KB_B"			,"ASCII_b"			,"ASCII_B"			,"ASCII_b"		,
	"KB_C"			,"ASCII_c"			,"ASCII_C"			,"ASCII_c"		,
	"KB_D"			,"ASCII_d"			,"ASCII_D"			,"ASCII_d"		,
	"KB_E"			,"ASCII_e"			,"ASCII_E"			,"ASCII_e"		,
	"KB_F"			,"ASCII_f"			,"ASCII_F"			,"ASCII_f"		,
	"KB_G"			,"ASCII_g"			,"ASCII_G"			,"ASCII_g"		,
	"KB_H"			,"ASCII_h"			,"ASCII_H"			,"ASCII_h"		,
	"KB_I"			,"ASCII_i"			,"ASCII_I"			,"ASCII_i"		,
	"KB_J"			,"ASCII_j"			,"ASCII_J"			,"ASCII_j"		,
	"KB_K"			,"ASCII_k"			,"ASCII_K"			,"ASCII_k"		,
	"KB_L"			,"ASCII_l"			,"ASCII_L"			,"ASCII_l"		,
	"KB_M"			,"ASCII_m"			,"ASCII_M"			,"ASCII_m"		,
	"KB_N"			,"ASCII_n"			,"ASCII_N"			,"ASCII_n"		,
	"KB_O"			,"ASCII_o"			,"ASCII_O"			,"ASCII_o"		,
	"KB_P"			,"ASCII_p"			,"ASCII_P"			,"ASCII_p"		,
	"KB_Q"			,"ASCII_q"			,"ASCII_Q"			,"ASCII_q"		,
	"KB_R"			,"ASCII_r"			,"ASCII_R"			,"ASCII_r"		,
	"KB_S"			,"ASCII_s"			,"ASCII_S"			,"ASCII_s"		,
	"KB_T"			,"ASCII_t"			,"ASCII_T"			,"ASCII_t"		,
	"KB_U"			,"ASCII_u"			,"ASCII_U"			,"ASCII_u"		,
	"KB_V"			,"ASCII_v"			,"ASCII_V"			,"ASCII_v"		,
	"KB_W"			,"ASCII_w"			,"ASCII_W"			,"ASCII_w"		,
	"KB_X"			,"ASCII_x"			,"ASCII_X"			,"ASCII_x"		,
	"KB_Y"			,"ASCII_y"			,"ASCII_Y"			,"ASCII_y"		,
	"KB_Z"			,"ASCII_z"			,"ASCII_Z"			,"ASCII_z"		,
	"KB_0"			,"ASCII_0"			,"ASCII_EQUALS"		,"ASCII_0"		,
	"KB_1"			,"ASCII_1"			,"ASCII_EXCLAMATION","ASCII_PIPE"	,
	"KB_2"			,"ASCII_2"			,"ASCII_QUOTE"		,"ASCII_AT"		,
	"KB_3"			,"ASCII_3"			,"ASCII_DOT"		,"ASCII_HASH"	,
	"KB_4"			,"ASCII_4"			,"ASCII_DOLLAR"		,"ASCII_CAGADILLA",
	"KB_5"			,"ASCII_5"			,"ASCII_PERCENT"	,"ASCII_5"		,
	"KB_6"			,"ASCII_6"			,"ASCII_AMPERSAND"	,"ASCII_BENDPIPE",
	"KB_7"			,"ASCII_7"			,"ASCII_SLASH"		,"ASCII_7"		,
	"KB_8"			,"ASCII_8"			,"ASCII_LPARENTHESIS","ASCII_8"		,
	"KB_9"			,"ASCII_9"			,"ASCII_RPARENTHESIS","ASCII_9"		,
	"KB_APOS"		,"ASCII_SINGLEQUOTE","ASCII_QUESTION"	,"ASCII_SINGLEQUOTE",
	"KB_EXCLAM"		,"ASCII_IEXCLAMATION","ASCII_IQUESTION"	,"ASCII_IEXCLAMATION",
	"KB_CONSOLE"	,"ASCII_NUM"		,"ASCII_ORD"		,"ASCII_BACKSLASH",
	"KB_COMMA"		,"ASCII_COMMA"		,"ASCII_SEMICOLON"	,"ASCII_COMMA"	,
	"KB_PERIOD"		,"ASCII_PERIOD"		,"ASCII_COLON"		,"ASCII_PERIOD"	,
	"KB_MINUS"		,"ASCII_MINUS"		,"ASCII_UNDERSCORE"	,"ASCII_MINUS"	,
	"KB_KPMINUS"	,"ASCII_MINUS"		,"ASCII_MINUS"		,"ASCII_MINUS"	,
	"KB_KPPLUS"		,"ASCII_PLUS"		,"ASCII_PLUS"		,"ASCII_PLUS"	,
	"KB_LBRACKET"	,"ASCII_ACCENT"		,"ASCII_CIRCUNFLEX"	,"ASCII_LBRACKET",
	"KB_RBRACKET"	,"ASCII_PLUS"		,"ASCII_ASTERISK"	,"ASCII_RBRACKET",
	"KB_LKEY"		,"ASCII_LKEY"		,"ASCII_LKEY"		,"ASCII_LKEY"	,
	"KB_RKEY"		,"ASCII_cedilla"	,"ASCII_CEDILLA"	,"ASCII_RKEY"	,
	"KB_ENYE"		,"ASCII_enye"		,"ASCII_ENYE"		,"ASCII_enye"	,
	"KB_BACKSPACE"	,"8"				,"8"				,"8"			,
	"KB_ENTER"		,"13"				,"13"				,"13"			,
	"KB_ESC"		,"27"				,"27"				,"27"			,
	"KB_SPACEBAR"	,"32"				,"32"				,"32"			,	
	/* new entries not below this line, terminator 0,0,0,0 MUST BE LAST DEFINED ENTRY*/
	NULL};

const char *keyNames[] = { 	
	"KB_TAB"		,"A"				,"B"				,"C"			,
	"D"				,"E"				,"F"				,"G"			,
	"H"				,"I"				,"J"				,"K"			,
	"L"				,"M"				,"N"				,"O"			,
	"P"				,"Q"				,"R"				,"S"			,
	"T"				,"U"				,"V"				,"W"			,
	"X"				,"Y"				,"Z"				,"0"			,
	"1"				,"2"				,"3"				,"4"			,
	"5"				,"6"				,"7"				,"8"			,
	"9"				,"KP_0"				,"KP_1"				,"KP_2"			,
	"KP_3"			,"KP_4"				,"KP_5"				,"KP_6"			,
	"KP_7"			,"KP_8"				,"KP_9"				,"F1"			,
	"F2"			,"F3"				,"F4"				,"F5"			,
	"F6"			,"F7"				,"F8"				,"F9"			,
	"F10"			,"F11"				,"F12"				,"ESC"			,
	"BACKSLASH"		,"MINUS"			,"ASCII_O"			,"BACKSPACE"	,
	"TAB"			,"ENTER"			,"ASCII_P"			,"ASCII_p"		,
	"COLON"			,"ASCII_q"			,"ASCII_Q"			,"LT"			,
	"COMMA"			,"ASCII_r"			,"SLASH"			,"SPACE"		,
	"INSERT"		,"DELETE"			,"HOME"				,"END"			,
	"PAGEUP"		,"PAGEDOWN"			,"LEFT"				,"RIGHT"		,
	"UP"			,"DOWN"				,"KP_SLASH"			,"ASTERISK"		,
	"KP_MINUS"		,"KP_PLUS"			,"KP_DELETE"		,"KP_ENTER"		,
	"PRINT"			,"PAUSE"			,"ASCII_W"			,"ASCII_w"		,
	"KB_X"			,"ASCII_x"			,"ASCII_X"			,"ASCII_x"		,
	"KB_Y"			,"ASCII_y"			,"ASCII_Y"			,"ASCII_y"		,
	"KB_Z"			,"SEMICOLON"		,"ASCII_Z"			,"ASCII_z"		,
	"KB_0"			,"ASCII_0"			,"ASCII_EQUALS"		,"ASCII_0"		,
	"KB_1"			,"ASCII_1"			,"ASCII_EXCLAMATION","SHIFT"		,
	"RSHIFT"		,"CONTROL"			,"RCONTROL"			,"ASCII_AT"		,
	"KB_3"			,"ASCII_3"			,"ASCII_DOT"		,"MENU"			,
	"SCROLL"		,"NUM"				,"CAPS"				,"ASCII_CAGADILLA",
	"KB_5"			,"ASCII_5"			,"ASCII_PERCENT"	,"ASCII_5"		,
	"KB_6"			,"ASCII_6"			,"ASCII_AMPERSAND"	,"ASCII_BENDPIPE",
	"KB_7"			,"ASCII_7"			,"ASCII_SLASH"		,"ASCII_7"		,
	"KB_8"			,"ASCII_8"			,"ASCII_LPARENTHESIS","ASCII_8"		,
	"KB_9"			,"ASCII_9"			,"ASCII_RPARENTHESIS","ASCII_9"		,
	"KB_APOS"		,"ASCII_SINGLEQUOTE","ASCII_QUESTION"	,"ASCII_SINGLEQUOTE",
	"KB_EXCLAM"		,"ASCII_IEXCLAMATION","ASCII_IQUESTION"	,"ASCII_IEXCLAMATION",
	"KB_CONSOLE"	,"ASCII_NUM"		,"ASCII_ORD"		,"ASCII_BACKSLASH",
	"KB_COMMA"		,"ASCII_COMMA"		,"ASCII_SEMICOLON"	,"ASCII_COMMA"	,
	"KB_PERIOD"		,"ASCII_PERIOD"		,"ASCII_COLON"		,"ASCII_PERIOD"	,
	"KB_MINUS"		,"ASCII_MINUS"		,"ASCII_UNDERSCORE"	,"ASCII_MINUS"	,
	"KB_KPMINUS"	,"ASCII_MINUS"		,"ASCII_MINUS"		,"ASCII_MINUS"	,
	"KB_KPPLUS"		,"ASCII_PLUS"		,"ASCII_PLUS"		,"ASCII_PLUS"	,
	"KB_LBRACKET"	,"ASCII_ACCENT"		,"ASCII_CIRCUNFLEX"	,"ASCII_LBRACKET",
	"KB_RBRACKET"	,"ASCII_PLUS"		,"ASCII_ASTERISK"	,"ASCII_RBRACKET",
	"KB_LKEY"		,"ASCII_LKEY"		,"ASCII_LKEY"		,"ASCII_LKEY"	,
	"KB_RKEY"		,"ASCII_cedilla"	,"ASCII_CEDILLA"	,"ASCII_RKEY"	,
	"KB_ENYE"		,"ASCII_enye"		,"ASCII_ENYE"		,"ASCII_enye"	,
	"KB_BACKSPACE"	,"8"				,"8"				,"8"			,
	"KB_ENTER"		,"13"				,"13"				,"13"			,
	"KB_ESC"		,"27"				,"27"				,"27"			,
	"KB_SPACEBAR"	,"32"				,"32"				,"32"			,	
	/* new entries not below this line, terminator 0,0,0,0 MUST BE LAST DEFINED ENTRY*/
	NULL};


int codepage[] = { 	
	//SCANCODE		ASCII CODES		SHIFT ASCII			ALTGR ASCII
	/*
	KB_TAB,		32,					32,					32,
	KB_A, 		ASCII_a,			ASCII_A,			ASCII_a,
	KB_B, 		ASCII_b,			ASCII_B,			ASCII_b,
	KB_C, 		ASCII_c,			ASCII_C,			ASCII_c,
	KB_D, 		ASCII_d,			ASCII_D,			ASCII_d,
	KB_E, 		ASCII_e,			ASCII_E,			ASCII_e,
	KB_F, 		ASCII_f,			ASCII_F,			ASCII_f,
	KB_G, 		ASCII_g,			ASCII_G,			ASCII_g,
	KB_H, 		ASCII_h,			ASCII_H,			ASCII_h,
	KB_I, 		ASCII_i,			ASCII_I,			ASCII_i,
	KB_J, 		ASCII_j,			ASCII_J,			ASCII_j,
	KB_K, 		ASCII_k,			ASCII_K,			ASCII_k,
	KB_L, 		ASCII_l,			ASCII_L,			ASCII_l,
	KB_M, 		ASCII_m,			ASCII_M,			ASCII_m,
	KB_N, 		ASCII_n,			ASCII_N,			ASCII_n,
	KB_O, 		ASCII_o,			ASCII_O,			ASCII_o,
	KB_P, 		ASCII_p,			ASCII_P,			ASCII_p,
	KB_Q, 		ASCII_q,			ASCII_Q,			ASCII_q,
	KB_R, 		ASCII_r,			ASCII_R,			ASCII_r,
	KB_S, 		ASCII_s,			ASCII_S,			ASCII_s,
	KB_T, 		ASCII_t,			ASCII_T,			ASCII_t,
	KB_U, 		ASCII_u,			ASCII_U,			ASCII_u,
	KB_V, 		ASCII_v,			ASCII_V,			ASCII_v,
	KB_W, 		ASCII_w,			ASCII_W,			ASCII_w,
	KB_X, 		ASCII_x,			ASCII_X,			ASCII_x,
	KB_Y, 		ASCII_y,			ASCII_Y,			ASCII_y,
	KB_Z, 		ASCII_z,			ASCII_Z,			ASCII_z,
	KB_0,		ASCII_0,			ASCII_EQUALS,		ASCII_0,
	KB_1,		ASCII_1,			ASCII_EXCLAMATION,	ASCII_PIPE,
	KB_2,		ASCII_2,			ASCII_QUOTE,		ASCII_AT,
	KB_3,		ASCII_3,			ASCII_DOT,			ASCII_HASH,
	KB_4,		ASCII_4,			ASCII_DOLLAR,		ASCII_CAGADILLA,
	KB_5,		ASCII_5,			ASCII_PERCENT,		ASCII_5,
	KB_6,		ASCII_6,			ASCII_AMPERSAND,	ASCII_BENDPIPE,
	KB_7,		ASCII_7,			ASCII_SLASH,		ASCII_7,
	KB_8,		ASCII_8,			ASCII_LPARENTHESIS,	ASCII_8,
	KB_9,		ASCII_9,			ASCII_RPARENTHESIS,	ASCII_9,
	KB_APOS,	ASCII_SINGLEQUOTE,	ASCII_QUESTION,		ASCII_SINGLEQUOTE,
	KB_EXCLAM,	ASCII_IEXCLAMATION,	ASCII_IQUESTION,	ASCII_IEXCLAMATION,
	KB_CONSOLE,	ASCII_NUM,			ASCII_ORD,			ASCII_BACKSLASH,
	KB_COMMA,	ASCII_COMMA,		ASCII_SEMICOLON,	ASCII_COMMA,
	KB_PERIOD,	ASCII_PERIOD,		ASCII_COLON,		ASCII_PERIOD,
	KB_MINUS,	ASCII_MINUS,		ASCII_UNDERSCORE,	ASCII_MINUS,
	KB_KPMINUS,	ASCII_MINUS,		ASCII_MINUS,		ASCII_MINUS,
	KB_KPPLUS,	ASCII_PLUS,			ASCII_PLUS,			ASCII_PLUS,
	KB_LBRACKET,ASCII_ACCENT,		ASCII_CIRCUNFLEX,	ASCII_LBRACKET,
	KB_RBRACKET,ASCII_PLUS,			ASCII_ASTERISK,		ASCII_RBRACKET,
	KB_LKEY,	ASCII_LKEY,			ASCII_LKEY,			ASCII_LKEY,
	KB_RKEY,	ASCII_cedilla,		ASCII_CEDILLA,		ASCII_RKEY,
	KB_ENYE,	ASCII_enye,			ASCII_ENYE,			ASCII_enye,
	KB_BACKSPACE,8,					8, 					8,
	KB_ENTER, 	13,					13, 				13,
	KB_ESC, 	27,					27, 				27,
	KB_SPACEBAR,32,					32,					32,	
	*/
	/* new entries not below this line, terminator 0,0,0,0 MUST BE LAST DEFINED ENTRY*/
	0,			0,					0,					0
};

